"use client";

/*
 * Drop It — P2P File Sharing Component
 * ======================================
 *
 * This is the heart of the application. It manages the entire lifecycle of a
 * peer-to-peer file transfer using WebRTC (via the PeerJS library):
 *
 *   1. Peer Identity — Every browser gets a unique random peer ID when the
 *      component mounts. This ID is how other peers find and connect to you.
 *
 *   2. Outbound Connection — The user enters a remote peer ID and clicks
 *      "Connect". The component initiates a WebRTC data channel to that peer.
 *
 *   3. Inbound Connection — When another peer connects to us, we respond
 *      by setting up a data channel listener on our side.
 *
 *   4. Sending Files — The user picks a file. We send a "metadata" message
 *      first (name, size, type, unique ID), then slice the file into 16 KB
 *      binary "chunk" messages, and finally send an "end" signal.
 *
 *   5. Receiving Files — We listen for the three message types above,
 *      accumulate chunks in memory, and reassemble them into a Blob when
 *      the "end" signal arrives. The user can then download the file.
 *
 *   6. Shareable Links — A URL containing our peer ID can be copied. If a
 *      visitor opens that URL, auto-connection kicks in.
 *
 * How WebRTC / PeerJS works (conceptually):
 *   - WebRTC browsers negotiate a direct P2P connection via a "signalling
 *     server". PeerJS provides a free hosted signalling server that helps
 *     peers discover each other by their random IDs.
 *   - Once the signalling handshake completes, data flows directly between
 *     browsers — no intermediary sees the file contents.
 *
 * File chunks:
 *   - Large files cannot be sent as a single message over WebRTC data
 *     channels (they may fail or cause memory issues). We split into 16 KB
 *     chunks and send them sequentially.
 *   - Each chunk is accompanied by the file's unique ID so the receiver can
 *     reassemble multiple files concurrently.
 */

import type React from "react";
import { useState, useRef, useEffect, useCallback } from "react";
import { Peer, type DataConnection } from "peerjs";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import {
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Input } from "@/components/ui/input";
import {
  Upload,
  Download,
  Copy,
  CheckCircle,
  X,
  Link as LinkIcon,
  FileText,
  Monitor,
  User,
  Loader2,
  Link,
} from "lucide-react";

/*
 * Each chunk is 16,384 bytes (16 KB). This size is chosen because:
 *   - WebRTC data channels have a maximum message size (typically ~256 KB
 *     but varies by browser). 16 KB is well within safe limits.
 *   - Smaller chunks allow granular progress reporting.
 *   - If a chunk fails, we only lose 16 KB, not the whole file.
 */
const CHUNK_SIZE = 16384;

/*
 * Represents a single file transfer (either incoming or outgoing).
 *
 * Fields:
 *   - id:       A random string generated by the sender used to correlate
 *               metadata / chunks / end signals for the same file.
 *   - name:     The original filename.
 *   - size:     Total file size in bytes (used for progress % calculation).
 *   - progress: A percentage value 0-100 shown in the progress bar.
 *   - type:     The MIME type (e.g. "image/png", "application/pdf").
 *   - status:   Current stage of the transfer.
 *                 "sending"    — we are uploading this file to the remote peer.
 *                 "receiving"  — we are downloading this file from the remote peer.
 *                 "completed"  — we finished sending the last chunk.
 *                 "ready"      — all chunks received, file is ready to save.
 *                 "error"      — something went wrong (unused currently).
 *   - url:      A blob:// URL created from the reassembled chunks (receiver
 *               side only). Used as the href for downloading.
 */
interface SharedFile {
  id: string;
  name: string;
  size: number;
  progress: number;
  status: "sending" | "receiving" | "completed" | "error" | "ready";
  type: string;
  url?: string;
}

/*
 * P2PShare — Main component
 * --------------------------
 * This component is marked "use client" because it relies on browser-only
 * APIs (WebRTC, FileReader, navigator.clipboard, URL.createObjectURL).
 *
 * State overview:
 *   - peerId / peer:  Our PeerJS identity. Created once on mount.
 *   - remoteId:       The peer ID the user wants to connect to.
 *   - connection:     The active DataConnection to the remote peer.
 *   - files:          Array of all transfers (in/out), drives the UI list.
 *   - isConnected:    Derived boolean for UI feedback.
 *   - isCopied:       Brief flash feedback when user copies ID/link.
 *
 * Refs (useRef instead of state to avoid re-renders on every chunk):
 *   - incomingChunks:  Accumulates binary chunks per file ID.
 *   - receivedSize:    Tracks how many bytes have arrived per file ID.
 *   - fileInputRef:    Reference to the hidden <input type="file">.
 */
export default function P2PShare() {
  const [peerId, setPeerId] = useState<string>("");
  const [remoteId, setRemoteId] = useState<string>("");
  const [peer, setPeer] = useState<Peer | null>(null);
  const [connection, setConnection] = useState<DataConnection | null>(null);
  const [files, setFiles] = useState<SharedFile[]>([]);
  const [isConnected, setIsConnected] = useState(false);
  const [isDisconnectedInMidTransfer, setIsDisconnectedInMidTransfer] =
    useState(false);
  const [isCopied, setIsCopied] = useState(false);

  /*
   * Refs for accumulating incoming file data.
   * We use refs instead of state because:
   *   - Chunks arrive very fast (potentially hundreds per second).
   *   - Updating React state on every chunk would cause excessive re-renders.
   *   - We only need this data when the transfer completes (to create the Blob).
   * We still call setFiles for progress updates, but throttled by React batching.
   */
  const incomingChunks = useRef<Record<string, Uint8Array[]>>({});
  const receivedSize = useRef<Record<string, number>>({});
  const fileInputRef = useRef<HTMLInputElement>(null);
  const connectionRef = useRef<DataConnection | null>(null);
  const lastPongTimestamp = useRef<number>(Date.now());
  const heartbeatIntervalRef = useRef<ReturnType<typeof setInterval> | null>(
    null,
  );

  /*
   * Effect: Create the PeerJS peer instance once on mount.
   *
   * PeerJS uses a free signalling server (0.peerjs.com by default) to
   * facilitate the WebRTC handshake. Once the handshake is done, data
   * flows directly P2P.
   *
   * Events:
   *   - "open":        The peer has registered with the signalling server
   *                    and received its unique ID.
   *   - "connection":  Another peer has initiated a connection to us.
   *   - "error":       Something went wrong (e.g. network issues, ID taken).
   *
   * Cleanup: We call newPeer.destroy() when the component unmounts to
   * prevent memory leaks.
   */
  useEffect(() => {
    const newPeer = new Peer();

    newPeer.on("open", (id) => {
      setPeerId(id);
      console.log("My peer ID is: " + id);
    });

    newPeer.on("connection", (conn) => {
      setupConnection(conn);
    });

    newPeer.on("error", (err) => {
      console.error("PeerJS error:", err);
    });

    setPeer(newPeer);

    return () => {
      newPeer.destroy();
    };
  }, []);

  /*
   * setupConnection — Attach event handlers to a DataConnection.
   *
   * This is called for BOTH outbound connections (user clicks Connect) AND
   * inbound connections (remote peer initiated). The same handler set is
   * reused because the protocol is symmetric.
   *
   * DataConnection events:
   *   - "open":  The WebRTC data channel is fully open. We can send data.
   *   - "data":  A message arrived. We use a custom protocol with three
   *              message types (metadata / chunk / end).
   *   - "close": The remote peer disconnected or the connection dropped.
   */
  const stopHeartbeat = useCallback(() => {
    if (heartbeatIntervalRef.current) {
      clearInterval(heartbeatIntervalRef.current);
      heartbeatIntervalRef.current = null;
    }
  }, []);

  const setupConnection = useCallback(
    (conn: DataConnection) => {
      setConnection(conn);
      connectionRef.current = conn;

      conn.on("open", () => {
        setIsConnected(true);
        setIsDisconnectedInMidTransfer(false);
        lastPongTimestamp.current = Date.now();

        stopHeartbeat();
        heartbeatIntervalRef.current = setInterval(() => {
          const c = connectionRef.current;
          if (!c || !c.open) {
            stopHeartbeat();
            return;
          }
          if (Date.now() - lastPongTimestamp.current > 7000) {
            c.close();
            return;
          }
          c.send({ type: "ping" });
        }, 3000);
      });

      conn.on("data", (data: any) => {
        if (data.type === "ping") {
          conn.send({ type: "pong" });
          return;
        }
        if (data.type === "pong") {
          lastPongTimestamp.current = Date.now();
          return;
        }

        if (data.type === "metadata") {
          const newFile: SharedFile = {
            id: data.id,
            name: data.name,
            size: data.size,
            type: data.fileType,
            progress: 0,
            status: "receiving",
          };
          setFiles((prev) => [newFile, ...prev]);
          incomingChunks.current[data.id] = [];
          receivedSize.current[data.id] = 0;
        } else if (data.type === "chunk") {
          const { id, chunk } = data;

          if (incomingChunks.current[id]) {
            const dataArray =
              chunk instanceof Uint8Array ? chunk : new Uint8Array(chunk);
            incomingChunks.current[id].push(dataArray);
            receivedSize.current[id] += dataArray.byteLength;

            setFiles((prev) =>
              prev.map((f) => {
                if (f.id === id) {
                  const progress = Math.min(
                    (receivedSize.current[id] / f.size) * 100,
                    99,
                  );
                  return { ...f, progress };
                }
                return f;
              }),
            );
          }
        } else if (data.type === "end") {
          const { id } = data;
          const chunks = incomingChunks.current[id];

          if (chunks && chunks.length > 0) {
            const finalChunks = [...chunks];

            setFiles((prev) => {
              const file = prev.find((f) => f.id === id);
              if (!file) return prev;

              const blob = new Blob(finalChunks as any, { type: file.type });
              const url = URL.createObjectURL(blob);

              return prev.map((f) =>
                f.id === id
                  ? {
                      ...f,
                      progress: 100,
                      status: "ready",
                      url,
                    }
                  : f,
              );
            });

            delete incomingChunks.current[id];
            delete receivedSize.current[id];
          } else {
            console.error(`Received 'end' for ${id} but no chunks were found!`);
          }
        }
      });

      conn.on("close", () => {
        stopHeartbeat();
        setIsConnected(false);
        setIsDisconnectedInMidTransfer(true);
        setConnection(null);
        connectionRef.current = null;
        setFiles((prev) =>
          prev.map((f) =>
            f.status === "sending" || f.status === "receiving"
              ? { ...f, status: "error" as const }
              : f,
          ),
        );
      });
    },
    [stopHeartbeat],
  );

  /*
   * handleDownload — Trigger a file save dialog for a received file.
   *
   * We create a temporary <a> element pointing to the blob URL and
   * programmatically click it. This is the standard browser approach
   * for triggering downloads from JavaScript (no popup blocker issues).
   */
  const handleDownload = (file: SharedFile) => {
    if (!file.url) return;
    const a = document.createElement("a");
    a.href = file.url;
    a.download = file.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  /*
   * handleConnect — Initiate an outbound WebRTC connection.
   *
   * peer.connect(remoteId) asks the PeerJS signalling server to broker a
   * connection to the peer with the given ID. If the remote peer exists and
   * is online, the "connection" event fires on their side and the "open"
   * event fires on both sides when the data channel is ready.
   */
  const handleConnect = () => {
    if (!peer || !remoteId) return;
    const conn = peer.connect(remoteId);
    setupConnection(conn);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(peerId);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  /*
   * handleFileChange — Read selected file(s) and send them chunk by chunk.
   *
   * This is where the sender-side logic lives:
   *
   *   1. Generate a unique ID for each file (used to correlate messages).
   *   2. Add the file to the local state so the UI shows a progress bar.
   *   3. Send a "metadata" message (name, size, type, id).
   *   4. Read the file in 16 KB slices using FileReader.
   *   5. Send each slice as a "chunk" message.
   *   6. After the last chunk, send an "end" signal.
   *   7. Mark the file as "completed" in local state.
   *
   * Why FileReader instead of Response / Blob.stream()?
   *   - FileReader is widely supported and gives us precise control over
   *     each chunk's byte boundaries.
   *   - The readNextChunk recursive pattern ensures chunks are sent one at
   *     a time without overwhelming the data channel.
   */
  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFiles = e.target.files;
    if (!selectedFiles || !connectionRef.current) return;

    for (let i = 0; i < selectedFiles.length; i++) {
      const file = selectedFiles[i];
      const fileId = Math.random().toString(36).substring(7);
      let aborted = false;

      setFiles((prev) => [
        {
          id: fileId,
          name: file.name,
          size: file.size,
          type: file.type,
          progress: 0,
          status: "sending",
        },
        ...prev,
      ]);

      connectionRef.current.send({
        type: "metadata",
        id: fileId,
        name: file.name,
        size: file.size,
        fileType: file.type,
      });

      const reader = new FileReader();
      let offset = 0;

      const readNextChunk = () => {
        const slice = file.slice(offset, offset + CHUNK_SIZE);
        reader.readAsArrayBuffer(slice);
      };

      reader.onload = (event) => {
        if (aborted) return;

        if (!connectionRef.current || !connectionRef.current.open) {
          aborted = true;
          setFiles((prev) =>
            prev.map((f) =>
              f.id === fileId ? { ...f, status: "error" as const } : f,
            ),
          );
          return;
        }

        if (event.target?.error) {
          console.error("FileReader error:", event.target.error);
          return;
        }

        const chunk = event.target?.result as ArrayBuffer;
        if (!chunk || chunk.byteLength === 0) {
          console.warn("Read empty chunk, skipping...");
        } else {
          connectionRef.current.send({
            type: "chunk",
            id: fileId,
            chunk: chunk,
          });
        }

        offset += chunk?.byteLength || 0;
        const progress = (offset / file.size) * 100;

        setFiles((prev) =>
          prev.map((f) => (f.id === fileId ? { ...f, progress } : f)),
        );

        if (offset < file.size) {
          readNextChunk();
        } else {
          if (connectionRef.current) {
            connectionRef.current.send({ type: "end", id: fileId });
          }
          setFiles((prev) =>
            prev.map((f) =>
              f.id === fileId ? { ...f, status: "completed" } : f,
            ),
          );
        }
      };

      readNextChunk();
    }
  };

  /*
   * handleCopyLink — Copy a shareable link to the clipboard.
   *
   * The link includes the current page origin + ?peerId=<our-id> so that
   * anyone who opens it will automatically attempt a connection to us.
   */
  const handleCopyLink = () => {
    const shareUrl = `${window.location.origin}/?peerId=${peerId}`;
    navigator.clipboard
      .writeText(shareUrl)
      .then(() => {
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 2000);
      })
      .catch((error) => {
        console.error("Failed to copy share link:", error);
        setIsCopied(false);
      });
  };

  /*
   * Effect: Auto-connect from URL parameter.
   *
   * When the page URL contains ?peerId=XXXX, we automatically fill in the
   * remote ID and initiate a connection. This is how shareable links work:
   * the recipient opens the link and gets connected without typing anything.
   *
   * Why is this a separate effect and not in the init effect?
   *   - The init effect runs once on mount when `peer` is null.
   *   - We need to wait until the peer is ready before connecting.
   *   - By depending on [peer, setupConnection], this effect fires only
   *     after the peer instance is set in state.
   */
  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const urlPeerId = urlParams.get("peerId");
    if (urlPeerId && peer) {
      setRemoteId(urlPeerId);
      const conn = peer.connect(urlPeerId);
      setupConnection(conn);
    }
  }, [peer, setupConnection]);

  return (
    <Card className="w-full max-w-2xl mx-auto shadow-lg border-2">
      <CardHeader className="flex flex-row bg-muted/50">
        <CardTitle className="gap-2 flex items-center">
          <Monitor className="w-6 h-6" />
          P2P File Transfer
        </CardTitle>
        <CardTitle className="ml-auto gap-2">
          {isCopied ? (
            <div className="flex items-center gap-1 text-sm text-green-500">
              <span>Link Copied</span>{" "}
              <CheckCircle className="w-4 h-4 text-green-500" />
            </div>
          ) : (
            <button
              onClick={handleCopyLink}
              disabled={!peerId || peerId === "Generating..."}
              className="flex items-center cursor-pointer gap-1 text-sm text-primary hover:underline disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Link className="w-4 h-4" />
              Share Link
            </button>
          )}
        </CardTitle>
      </CardHeader>

      <CardContent className="space-y-6 pt-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-2">
            <label className="text-sm font-medium flex items-center gap-2">
              <User className="w-4 h-4" /> Your ID
            </label>
            <div className="flex gap-2">
              <Input
                value={peerId || "Generating..."}
                readOnly
                className="font-mono text-xs bg-muted"
              />
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-sm font-medium flex items-center gap-2">
              <LinkIcon className="w-4 h-4" /> Remote Peer ID
            </label>
            <div className="flex gap-2">
              <Input
                placeholder="Paste Peer ID..."
                value={remoteId}
                onChange={(e) => setRemoteId(e.target.value)}
                disabled={isConnected}
                className="font-mono text-xs"
              />
              <Button
                onClick={handleConnect}
                disabled={isConnected || !remoteId}
              >
                {isConnected ? "Connected" : "Connect"}
              </Button>
            </div>
          </div>
        </div>

        <Separator />

        <div
          className={`
            border-2 border-dashed rounded-xl p-10 text-center transition-colors
            ${isConnected ? "cursor-pointer hover:bg-muted/50 border-primary/20" : "bg-muted/20 border-muted opacity-50 cursor-not-allowed"}
          `}
          onClick={() => isConnected && fileInputRef.current?.click()}
        >
          <input
            type="file"
            accept="*/*"
            ref={fileInputRef}
            onChange={handleFileChange}
            className="hidden"
            multiple
          />
          <Upload
            className={`w-12 h-12 mx-auto mb-4 ${isConnected ? "text-primary" : "text-muted-foreground"}`}
          />
          <h3 className="text-lg font-semibold">
            {isConnected
              ? "Click to share a file"
              : "Connect to a peer to share files"}
          </h3>
          <p className="text-sm text-muted-foreground mt-2">
            Files are sent directly from your device to theirs.
          </p>
        </div>

        {isConnected && (
          <div className="flex items-center justify-center gap-2 text-green-600 bg-green-50 py-2 rounded-full border border-green-100">
            <CheckCircle className="w-4 h-4" />
            <span className="text-sm font-medium">
              Stable P2P Connection Established
            </span>
          </div>
        )}
        {isDisconnectedInMidTransfer && (
          <div className="flex items-center justify-center gap-2 text-red-600 bg-red-50 py-2 rounded-full border border-red-100">
            <span className="text-sm px-2 m-2 font-medium">
              Connection Lost During Transfer. May be your peer disconnected or
              network dropped. Please try again.
            </span>
          </div>
        )}

        {files.length > 0 && (
          <div className="space-y-3">
            <h4 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
              Transfers
            </h4>
            <div className="space-y-2 max-h-75 overflow-y-auto pr-2">
              {files.map((file) => (
                <div key={file.id} className="p-3 border rounded-lg bg-card">
                  <div className="flex items-center justify-between mb-2">
                    <div className="flex items-center gap-3">
                      <div className="p-2 bg-primary/10 rounded-md">
                        {file.status === "receiving" ||
                        file.status === "ready" ? (
                          <Download className="w-4 h-4 text-primary" />
                        ) : (
                          <FileText className="w-4 h-4 text-primary" />
                        )}
                      </div>
                      <div>
                        <div className="text-sm font-medium truncate max-w-37.5">
                          {file.name}
                        </div>
                        <div className="text-[10px] text-muted-foreground uppercase">
                          {(file.size / 1024 / 1024).toFixed(2)} MB •{" "}
                          {file.status === "ready" ? "Available" : file.status}
                        </div>
                      </div>
                    </div>
                    {file.status === "completed" && (
                      <CheckCircle className="w-5 h-5 text-green-500" />
                    )}
                    {file.status === "ready" && (
                      <Button
                        size="sm"
                        variant="default"
                        className="h-8 gap-1 px-2"
                        onClick={() => handleDownload(file)}
                      >
                        <Download className="w-3.5 h-3.5" />
                        Save
                      </Button>
                    )}
                    {(file.status === "sending" ||
                      file.status === "receiving") && (
                      <Loader2 className="w-5 h-5 animate-spin text-primary" />
                    )}
                  </div>
                  <Progress value={file.progress} className="h-1.5" />
                </div>
              ))}
            </div>
          </div>
        )}
      </CardContent>

      <CardFooter className="bg-muted/30 text-[10px] text-center justify-center text-muted-foreground">
        No server involved. Data stays in your browser.
      </CardFooter>
    </Card>
  );
}
